### ISSUE TITLE
terraform apply erro

### ISSUE THREAD

**Issue by ddias00** [rancher/terraform-aws-rke2#139] opened 2024-02-16 19:26 UTC
![image](https://github.com/rancher/terraform-aws-rke2/assets/17050697/aa7f5cc8-673f-46d1-bb3d-66d91182967d)

**Comment by matttrach** [comment] 2024-02-21 19:16
It looks like you are attempting to use and image that requires a subscription. There are a few of those in the server types, most are free to subscribe (I think the CIS image is an exception), I would try following that link and subscribing to the image then try running it again.

**Comment by matttrach** [comment] 2024-02-21 19:18
The main idea of setting images in the server/image types is so that users are on a very similar image than what we test on. This avoids some confusion and helps us reproduce errors.

**Comment by matttrach** [comment] 2024-02-21 19:35
Not all images we test on are free, and some require subscription even though they are free.
Unfortunately, there is no automated way that I have found to subscribe to AWS marketplace products, it is a one time setup that you have to do manually in the browser.

**Comment by matttrach** [comment] 2024-02-21 20:23
here is a link to the documentation for the subscription: https://docs.aws.amazon.com/m2/latest/userguide/mf-runtime-setup-ami.html

Here is the link to subscribe to the images: 
- https://aws.amazon.com/marketplace/server/procurement?productId=ca1fe94d-9237-41c7-8fc8-78b6b0658c9f
- https://aws.amazon.com/marketplace/pp/prodview-o5wqlcnuzvyv2?sr=0-5&ref_=beagle&applicationId=AWSMPContessa
- https://aws.amazon.com/marketplace/pp/prodview-iftkyuwv2sjxi?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

From all that I can tell the other images don't require subscription.

**Comment by matttrach** [comment] 2024-03-13 17:25
OMG, I am so sorry!! I found the bug you are describing and I am working on a resolution. 

It appears that in some regions the ubuntu 22 image search is pulling up a random other software.
To prevent this I am updating the search filters on all the images, getting them approved by out QA team, and adding a step in the pre-release workflow to validate that the images being pulled are the appropriate ones. 

It seems like if the search query is not valid for some reason AWS will ignore filters and return all software. I am not sure how this query which has been working is suddenly not valid, but I am going to refine it further and add tests to ensure that I am aware when things break. 

@ddias00 I am so sorry! I will have a resolution to this by the end of the week.
Thank you so much for your time, I understand now that my previous responses must have been very frustrating. I will work to make sure it doesn't happen again.

**Comment by matttrach** [comment] 2024-03-13 21:18
Here is the fix: https://github.com/rancher/terraform-aws-server/pull/57

**Comment by matttrach** [comment] 2024-03-18 17:43
this is resolved in v0.1.22

**Closed** 2024-04-09 17:50 UTC
